### ISSUE TITLE
Form Crashes if user presses Delete from leftmost char position

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/student-registration#112]
to reproduce:
1. Load the form
2. Complete to the point of a free text field
3. Active the cursor in that field
4. press 'backspace'
Result:
Crash/error that can't be recovered without complete reload (see screenshot)
![image (2)](https://user-images.githubusercontent.com/1458369/126848876-6d2896a8-f732-429b-9fc0-de86c7ce1a15.png)

**Comment by matthewjerome** [comment]
**fixed in #91**
