### ISSUE TITLE
Salesforce error when submitting a new student registration

### ISSUE THREAD

**Issue by MarcHenriA** [AmericaSCORESBayArea/student-registration#208]
### Salesforce error when submitting a new student registration

**-Reproduction steps**
1.	Open  https://student-registration-prod.herokuapp.com/ in desktop browser 
2.	Choose Parent/Guardian 
3.	View form 
4.	Enter new student record and see below what was entered
5.	Submit
Result: (Oops! Something went wrong! [1] Error: Request failed with status code 500)
Expectation: If the user entered something unacceptable the system should instruct the user how to correct it or what to do. In a case of a duplicate record being blocked, the system should invite the returning user to authenticate and update the existing student record.

**-Error found in salesforce response**

Error Details February 28,2022
12:36:22.000     02/28/2022     Worker-0     [MuleRuntime].uber.83: [salesforce-data-api-prod].post:\contacts:application\json:salesforce-data-api-config.BLOCKING @158874f3     DEBUG
event:162d65e0-98d6-11ec-a9a2-02328102feea Receiving response from Salesforce. Arguments: {endpoint=https://americascoresbayarea.my.salesforce.com/services/Soap/u/48.0/00D50000000NVw6, response=<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="urn:partner.soap.sforce.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sf="urn:sobject.partner.soap.sforce.com"><soapenv:Header><LimitInfoHeader><limitInfo><current>1964</current><limit>120000</limit><type>API REQUESTS</type></limitInfo></LimitInfoHeader></soapenv:Header><soapenv:Body><createResponse><result><errors xsi:type="DuplicateError"><message>Use one of these records? (Student Dupe)</message><statusCode>DUPLICATES_DETECTED</statusCode><duplicateResult><allowSave>true</allowSave><duplicateRule>Student_Contact_Duplicate_Rule</duplicateRule><duplicateRuleEntityType>Contact</duplicateRuleEntityType><errorMessage>Use one of these records? (Student Dupe)</errorMessage><matchResults><entityType>Contact</entityType><matchEngine>FuzzyMatchEngine</matchEngine><matchRecords><fieldDiffs><difference>SAME</difference><name>Contact_Type__c</name></fieldDiffs><fieldDiffs><difference>DIFFERENT</difference><name>LastName</name></fieldDiffs><fieldDiffs><difference>DIFFERENT</difference><name>FirstName</name></fieldDiffs><matchConfidence>99.0</matchConfidence><record xsi:type="sf:sObject"><sf:type>Contact</sf:type><sf:Id>0031T00004NGuVDQA1</sf:Id><sf:Name>Tes3Feb28 Hayward3</sf:Name><sf:Contact_Type__c>SCORES Student</sf:Contact_Type__c><sf:OwnerId>0051T000009eHfvQAE</sf:OwnerId><sf:LastModifiedDate>2022-02-28T20:15:31.000Z</sf:LastModifiedDate><sf:Id>0031T00004NGuVDQA1</sf:Id></record></matchRecords><rule>Student_Full_Name_matching</rule><size>1</size><success>true</success></matchResults></duplicateResult></errors><id xsi:nil="true"/><success>false</success></result></createResponse></soapenv:Body></soapenv:Envelope>}.

----
xmlns:sobj="urn:sobject.partner.soap.sforce.com"><m:sObjects><sobj:type xsi:type="xsd:string">Contact</sobj:type><sobj:LastName xsi:type="xsd:string">Hayward4</sobj:LastName><sobj:FirstName xsi:type="xsd:string">Tes4Feb28</sobj:FirstName><sobj:MiddleName xsi:type="xsd:string"></sobj:MiddleName><sobj:RecordTypeId xsi:type="xsd:string">01250000000VBbXAAW</sobj:RecordTypeId><sobj:MailingStreet xsi:type="xsd:string"></sobj:MailingStreet><sobj:MailingCity xsi:type="xsd:string"></sobj:MailingCity><sobj:MailingState xsi:type="xsd:string"></sobj:MailingState><sobj:MailingPostalCode xsi:type="xsd:string">0</sobj:MailingPostalCode><sobj:MailingCountry xsi:type="xsd:string">US</sobj:MailingCountry><sobj:HomePhone xsi:type="xsd:string"></sobj:HomePhone><sobj:Email xsi:type="xsd:string"></sobj:Email><sobj:Birthdate xsi:type="xsd:date">2015-02-28T00:00:00.000Z</sobj:Birthdate><sobj:Gender__c xsi:type="xsd:string">Female</sobj:Gender__c><sobj:Allergies__c xsi:type="xsd:string"></sobj:Allergies__c><sobj:Emergency_Contact_Name_Phone_01__c xsi:type="xsd:string">5168483324</sobj:Emergency_Contact_Name_Phone_01__c><sobj:Emergency_Contact_Name__c xsi:type="xsd:string">Feb28 Test4</sobj:Emergency_Contact_Name__c><sobj:Emergency_Contact_Relationship_to_Child__c xsi:type="xsd:string">Legal Guardian</sobj:Emergency_Contact_Relationship_to_Child__c><sobj:Ethnicity__c xsi:type="xsd:string">Native American</sobj:Ethnicity__c><sobj:Grade__c xsi:type="xsd:string">2nd</sobj:Grade__c><sobj:School_Attending__c xsi:type="xsd:string">Fairview Elementary School</sobj:School_Attending__c><sobj:Parent_Email_Address__c xsi:type="xsd:string">test4Feb@yahoo.fr</sobj:Parent_Email_Address__c><sobj:Parent_First_Name__c xsi:type="xsd:string">Feb28Test</sobj:Parent_First_Name__c><sobj:Parent_Home_Language__c xsi:type="xsd:string">Hmong</sobj:Parent_Home_Language__c><sobj:Parent_Last_Name__c xsi:type="xsd:string">Test4</sobj:Parent_Last_Name__c><sobj:Parent_Other_Language__c xsi:type="xsd:string"></sobj:Parent_Other_Language__c><sobj:Parent_Phone_01__c xsi:type="xsd:string">4627239683</sobj:Parent_Phone_01__c><sobj:Parent_Phone_02__c xsi:type="xsd:string"></sobj:Parent_Phone_02__c><sobj:Parent_Phone_03__c xsi:type="xsd:string"></sobj:Parent_Phone_03__c><sobj:Parent_Relationship_to_Child__c xsi:type="xsd:string">Grandparent</sobj:Parent_Relationship_to_Child__c><sobj:Reduced_Price_Lunch__c xsi:type="xsd:string">Yes</sobj:Reduced_Price_Lunch__c><sobj:Second_Emerg_Contact_Relationship_Child__c xsi:type="xsd:string"></sobj:Second_Emerg_Contact_Relationship_Child__c><sobj:Second_Emergency_Contact_Name__c xsi:type="xsd:string"></sobj:Second_Emergency_Contact_Name__c><sobj:Second_Emergency_Phone_01__c xsi:type="xsd:string"></sobj:Second_Emergency_Phone_01__c><sobj:Second_Emergency_Phone_02__c xsi:type="xsd:string"></sobj:Second_Emergency_Phone_02__c><sobj:Volunteer_for_this_Program_Parent__c xsi:type="xsd:string">No</sobj:Volunteer_for_this_Program_Parent__c><sobj:Contact_Type__C xsi:type="xsd:string">SCORES Student</sobj:Contact_Type__C><sobj:AccountId xsi:type="xsd:string">0011T00002O0xWLQAZ</sobj:AccountId></m:sObjects></m:create></env:Body></env:Envelope>, endpoint=https://americascoresbayarea.my.salesforce.com/services/Soap/u/48.0/00D50000000NVw6}.

**Comment by CritiqalPete** [comment]
For now because this is originating at the API level we are going to disable the checks there until we can sort out what the UX needs to be
